#ifndef DECODER_SDK_DEFINE_H
#define DECODER_SDK_DEFINE_H

#ifndef DECODER_SDK_NAMESPACE_BEGIN
#define DECODER_SDK_NAMESPACE_BEGIN namespace decoder_sdk {
#define DECODER_SDK_NAMESPACE_END }
#endif

#ifndef INTERNAL_NAMESPACE_BEGIN
#define INTERNAL_NAMESPACE_BEGIN namespace internal {
#define INTERNAL_NAMESPACE_END }
#endif

#endif // DECODER_SDK_DEFINE_H